### PR TITLE
Debug the CSS 3 transitions dectection function - Now fallback is fired

### PR DESCRIPTION
**Pull request by SBoudrias**
There was an issue bypassing the CSS 3 transitions fallback in older browser.

So I've changed transitionSupport() function with adaptaton of Modernizr project cssTransitions detection rules.

### CODE REVIEW

**Comment by SBoudrias** [comment]
Thinking this code back, I'll update it to make sur the transition detection is cached in a var so that the script don't have to run each time it's called.

**Comment by arielsalminen** [comment]
This is great! Just tested your pull request and it fixes the fallback in IE8/9.

**Comment by ramansharma89** [comment]
Thanks a lot friend. I solved my IE 8/9 issue. :+1:

**Comment by Mahesh2base** [comment]
Issue #79: Slides not sliding in IE 8 and IE 9.

**Pull request closed without merging**
